In [4]:
import numpy as np

In [10]:
A = np.array([[1,2,3],[3,2,1]], dtype=float)

In [11]:
B = np.array([[2,1,5],[5,2,4]], dtype=float)

In [57]:
A.shape

(2, 3)

In [21]:
np.matmul(A,B.transpose())

array([[19., 21.],
       [13., 23.]])

In [58]:
B.shape

(2, 3)

In [14]:
A - B

array([[-1.,  1., -2.],
       [-2.,  0., -3.]])

In [15]:
 A + B 

array([[3., 3., 8.],
       [8., 4., 5.]])

In [17]:
A / B

array([[0.5 , 2.  , 0.6 ],
       [0.6 , 1.  , 0.25]])

In [40]:
arrayOfMatricies = np.append(A,B,axis=0)

In [46]:
arrayOfMatricies

array([[1., 2., 3.],
       [3., 2., 1.],
       [2., 1., 5.],
       [5., 2., 4.]])

In [48]:
arrayOfMatricies = np.array([A,B])

In [51]:
arrayOfMatricies.shape

(2, 2, 3)

In [55]:
np.dstack((B,A)).shape

(2, 3, 2)

In [60]:
T = list([A,B, A+B, A-B])

In [61]:
T

[array([[1., 2., 3.],
        [3., 2., 1.]]), array([[2., 1., 5.],
        [5., 2., 4.]]), array([[3., 3., 8.],
        [8., 4., 5.]]), array([[-1.,  1., -2.],
        [-2.,  0., -3.]])]

In [62]:
T.append(np.array(T))

In [63]:
T

[array([[1., 2., 3.],
        [3., 2., 1.]]), array([[2., 1., 5.],
        [5., 2., 4.]]), array([[3., 3., 8.],
        [8., 4., 5.]]), array([[-1.,  1., -2.],
        [-2.,  0., -3.]]), array([[[ 1.,  2.,  3.],
         [ 3.,  2.,  1.]],
 
        [[ 2.,  1.,  5.],
         [ 5.,  2.,  4.]],
 
        [[ 3.,  3.,  8.],
         [ 8.,  4.,  5.]],
 
        [[-1.,  1., -2.],
         [-2.,  0., -3.]]])]

In [31]:
input_layer = [7,8,9]
for i, j in enumerate(input_layer):
    print('i: {}, j {}'.format(i,j))

i: 0, j 7
i: 1, j 8
i: 2, j 9


In [32]:
arrayOfMatricies[-1]

array([[2., 1., 5.],
       [5., 2., 4.]])

In [64]:
l = [1,2,3]

In [66]:
l = l[1:]

In [67]:
l

[2, 3]

In [68]:
np.exp(1)

2.718281828459045

In [69]:
x = 5
np.exp(x)

148.4131591025766

In [70]:
np.exp(-x)

0.006737946999085467

In [74]:
import random
random.shuffle(arrayOfMatricies[0])

In [75]:
arrayOfMatricies[0]

array([[1., 2., 3.],
       [1., 2., 3.]])

In [78]:
l = np.array([1,2,3])
random.shuffle(l)
l

array([3, 1, 2])

In [79]:
l[:-1]

array([3, 1])

In [80]:
reversed(l)

In [81]:
reversed(l)[:]

TypeError: 'reversed' object is not subscriptable

In [82]:
[i for i in reversed(l)]

[2, 1, 3]

In [84]:
t = np.array([[1],[2],[3]])

In [86]:
t.shape

(3, 1)

In [89]:
T = t.transpose()

In [90]:
T

array([[1, 2, 3]])

In [93]:
np.matmul(np.array([2]),T)

array([2, 4, 6])

In [96]:
np.matmul([1], [[1,2]])

array([1, 2])

In [101]:
l = [3,2,1]

In [104]:
l.pop()

1

In [105]:
l

[3, 2]