In [58]:
import numpy as np
import random
from sys import stdout
import difflib
from IPython.core.display import display, HTML, clear_output
from NeuralNetwork import NeuralNetwork as NN

In [59]:
k=0

In [60]:
nn = NN(2, [4], 2)
answerkey = [True,False]

In [61]:
answerkey[nn.predict([0.8,0.1]).argmax()]

False

In [62]:
out1 = str(nn)


In [63]:
data = [{'target':[0.1,0.8], 'input':[0.1,0.1]},
        {'target':[0.8,0.1], 'input':[0.1,0.8]},
        {'target':[0.8,0.1], 'input':[0.8,0.1]},
        {'target':[0.1,0.8], 'input':[0.8,0.8]}
       ]

In [65]:
i = 0
while i < 1000:
    clear_output()
    out1 = str(nn)
    i += 1
    random.shuffle(data)
    for d in data:
        nn.train(d['input'],d['target'])
    out2 = str(nn)
    display(HTML(difflib.HtmlDiff().make_file(out1.splitlines(), out2.splitlines())))
        

In [54]:
k += i
print('{} cycles'.format(k))
print(nn.predict([0.1,0.1]), not answerkey[nn.predict([0.1,0.1]).argmax()] )
print(nn.predict([0.1,0.8]), answerkey[nn.predict([0.1,0.8]).argmax()] )
print(nn.predict([0.8,0.1]), answerkey[nn.predict([0.8,0.1]).argmax()] )
print(nn.predict([0.8,0.8]), not answerkey[nn.predict([0.8,0.8]).argmax()] )

1 cycles
[[0.79191721]
 [0.83905774]] True
[[0.81228304]
 [0.85725593]] False
[[0.82630538]
 [0.85826272]] False
[[0.84183525]
 [0.87269509]] True


In [55]:
display(HTML(difflib.HtmlDiff().make_file(out1.splitlines(), out2.splitlines())))

In [67]:
difflib.HtmlDiff().make_table(out1.splitlines(), out2.splitlines())

'\n    <table class="diff" id="difflib_chg_to1026__top"\n           cellspacing="0" cellpadding="0" rules="groups" >\n        <colgroup></colgroup> <colgroup></colgroup> <colgroup></colgroup>\n        <colgroup></colgroup> <colgroup></colgroup> <colgroup></colgroup>\n        \n        <tbody>\n            <tr><td class="diff_next" id="difflib_chg_to1026__0"><a href="#difflib_chg_to1026__0">f</a></td><td class="diff_header" id="from1026_1">1</td><td nowrap="nowrap">Weight&nbsp;Matrix[0]:</td><td class="diff_next"><a href="#difflib_chg_to1026__0">f</a></td><td class="diff_header" id="to1026_1">1</td><td nowrap="nowrap">Weight&nbsp;Matrix[0]:</td></tr>\n            <tr><td class="diff_next" id="difflib_chg_to1026__1"><a href="#difflib_chg_to1026__1">n</a></td><td class="diff_header" id="from1026_2">2</td><td nowrap="nowrap">[[&nbsp;0.00835<span class="diff_chg">525</span>&nbsp;&nbsp;0.3052<span class="diff_sub">03</span>7<span class="diff_chg">8</span>]</td><td class="diff_next"><a href="